# Generated by Django 3.2.9 on 2021-11-28 16:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='available_in_countries',
            field=models.ManyToManyField(blank=True, to='films.Country'),
        ),
        migrations.AlterField(
            model_name='film',
            name='director',
            field=models.ManyToManyField(blank=True, to='films.Director'),
        ),
        migrations.AlterField(
            model_name='film',
            name='release_date',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
