# Generated by Django 3.2.9 on 2021-11-28 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_auto_20211128_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='director',
            field=models.ManyToManyField(blank=True, to='films.Director'),
        ),
    ]
