# Generated by Django 3.2.9 on 2021-11-28 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0006_auto_20211128_1917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='director',
            name='film',
        ),
        migrations.AddField(
            model_name='film',
            name='director',
            field=models.ManyToManyField(default='', to='films.Director'),
        ),
    ]
