# Generated by Django 3.2.9 on 2021-11-28 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0007_auto_20211128_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='director',
        ),
        migrations.AddField(
            model_name='director',
            name='film',
            field=models.ManyToManyField(to='films.Film'),
        ),
    ]
