# Generated by Django 3.2.9 on 2021-11-30 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0010_ratingfilm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ratingfilm',
            old_name='owner',
            new_name='user',
        ),
        migrations.AddField(
            model_name='ratingfilm',
            name='rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1),
            preserve_default=False,
        ),
    ]
